site_name: CEOS Tutorials
site_url: https://ceos-university-of-alberta.github.io/ceos_tutorials/ 
site_author: Ronny A. Hernández Mora
theme:
   name: material
markdown_extensions:
   - toc:
      permalink: []
